<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'WSO Smart Home Hub',
                'slug' => 'wso-smart-home-hub',
                'category' => 'Smart Home',
                'short_description' => 'Pusat kendali otomatis untuk seluruh perangkat pintar di rumah Anda.',
                'description' => 'WSO Smart Home Hub adalah perangkat pusat kendali yang menghubungkan semua perangkat pintar di rumah Anda ke dalam satu sistem yang terpadu. Dengan teknologi AI terbaru, hub ini mempelajari pola penggunaan Anda dan mengoptimalkan konsumsi energi secara otomatis. Mendukung lebih dari 200 merek perangkat smart home, mudah diatur melalui aplikasi mobile, dan kompatibel dengan asisten suara utama.',
                'specifications' => json_encode([
                    'Processor' => 'Quad-core 1.5GHz',
                    'Memory' => '2GB RAM, 8GB Storage',
                    'Connectivity' => 'WiFi 6, Bluetooth 5.0, Zigbee 3.0, Z-Wave',
                    'Power' => 'DC 5V/2A via USB-C',
                    'Dimensions' => '120 x 120 x 35mm',
                    'Weight' => '180g',
                ]),
                'features' => json_encode([
                    'Koneksi multi-protokol untuk kompatibilitas luas',
                    'AI-powered automation & learning',
                    'Kontrol suara dengan Google Assistant & Alexa',
                    'Energi efisien dengan mode sleep otomatis',
                    'Enkripsi end-to-end untuk keamanan data',
                    'OTA updates untuk fitur terbaru',
                ]),
                'image' => 'products/smart-hub.jpg',
                'gallery' => json_encode(['products/smart-hub-1.jpg', 'products/smart-hub-2.jpg', 'products/smart-hub-3.jpg']),
                'price' => 2500000,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'WSO Security Camera Pro',
                'slug' => 'wso-security-camera-pro',
                'category' => 'Security',
                'short_description' => 'Kamera pengawas 4K dengan night vision dan deteksi AI canggih.',
                'description' => 'WSO Security Camera Pro memberikan kualitas gambar Ultra HD 4K dengan detail yang tajam. Dilengkapi dengan night vision infra-merah hingga 30 meter, deteksi gerakan berbasis AI yang dapat membedakan manusia, hewan, dan kendaraan, serta audio dua arah untuk komunikasi langsung. Kamera ini tahan cuaca (IP67) sehingga cocok untuk penggunaan indoor maupun outdoor.',
                'specifications' => json_encode([
                    'Resolution' => '4K UHD (3840 x 2160)',
                    'Lens' => '2.8mm wide-angle, 110° FOV',
                    'Night Vision' => 'IR LED hingga 30m, Full Color mode',
                    'Connectivity' => 'WiFi 2.4/5GHz, Ethernet',
                    'Storage' => 'Cloud storage + slot microSD hingga 256GB',
                    'Protection' => 'IP67 Weatherproof',
                    'Power' => 'DC 12V/1A atau PoE',
                ]),
                'features' => json_encode([
                    '4K Ultra HD dengan HDR untuk gambar jernih',
                    'Deteksi AI untuk manusia, hewan, kendaraan',
                    'Night vision full color & infrared',
                    'Audio dua arah dengan noise cancellation',
                    'Notifikasi real-time ke smartphone',
                    'Integrasi dengan Google Home & Alexa',
                ]),
                'image' => 'products/security-camera.jpg',
                'gallery' => json_encode(['products/camera-1.jpg', 'products/camera-2.jpg']),
                'price' => 3200000,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'WSO Smart Thermostat',
                'slug' => 'wso-smart-thermostat',
                'category' => 'Climate Control',
                'short_description' => 'Termostat cerdas dengan kontrol suhu presisi dan penghematan energi.',
                'description' => 'WSO Smart Thermostat dirancang untuk memberikan kenyamanan optimal sekaligus mengurangi konsumsi energi hingga 30%. Dengan sensor suhu dan kelembaban yang akurat, jadwal mingguan yang fleksibel, dan kontrol jarak jauh via aplikasi, Anda dapat memastikan rumah selalu dalam kondisi ideal sebelum tiba. Layar sentuh OLED yang intuitif dan desain minimalis menjadikannya cocok untuk任何 rumah.',
                'specifications' => json_encode([
                    'Display' => 'OLED 3.5" Capacitive Touch',
                    'Temperature Range' => '5°C - 35°C',
                    'Humidity Sensor' => 'Accuracy ±2%',
                    'Connectivity' => 'WiFi 802.11b/g/n, Zigbee',
                    'Power' => 'AC 100-240V, battery backup 2xAAA',
                    'Compatibility' => 'HVAC systems: AC, Heat Pump, Boiler',
                    'Dimensions' => '86 x 86 x 25mm',
                ]),
                'features' => json_encode([
                    'Kontrol suhu presisi dengan akurasi ±0.5°C',
                    'Schedule mingguan & holiday mode',
                    'Geofencing untuk auto-adjust saat meninggalkan rumah',
                    'Laporan penggunaan energi harian/mingguan',
                    'Kompatibel dengan sebagian besar sistem HVAC',
                    'DIY installation dengan panduan video',
                ]),
                'image' => 'products/smart-thermostat.jpg',
                'gallery' => json_encode(['products/thermostat-1.jpg', 'products/thermostat-2.jpg']),
                'price' => 1850000,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'name' => 'WSO Smart Lock Pro',
                'slug' => 'wso-smart-lock-pro',
                'category' => 'Access Control',
                'short_description' => 'Kunci pintu pintar dengan 5 metode akses: sidik jari, PIN, RFID, App, dan kunci cadangan.',
                'description' => 'WSO Smart Lock Pro mengubah smartphone Anda menjadi kunci pintar dengan 5 metode akses yang aman: sidik jari, PIN numerik, kartu RFID, aplikasi mobile, dan kunci cadangan tradisional. Dengan enkripsi AES-256 dan protokol anti-pry, kunci ini memberikan keamanan tingkat tinggi untuk rumah Anda. Log aktivitas akan tercatat otomatis sehingga Anda selalu tahu siapa yang masuk dan keluar.',
                'specifications' => json_encode([
                    'Access Methods' => 'Fingerprint, PIN, RFID, App, Physical Key',
                    'Fingerprint Capacity' => 'Up to 100 fingerprints',
                    'PIN Length' => '4-8 digits',
                    'RFID Frequency' => '13.56MHz',
                    'Battery' => '4x AA, lifetime ~12 months',
                    'Connectivity' => 'Bluetooth 5.0, optional WiFi bridge',
                    'Door Compatibility' => '40-100mm door thickness',
                ]),
                'features' => json_encode([
                    'Sensor sidik jari responsif < 0.3 detik',
                    '50 kartu RFID + 100 sidik jari + PIN',
                    'Log aktivitas masuk/keluar real-time',
                    'Kunci darurat fisik sebagai backup',
                    'Notifikasi baterai rendah & upaya akses gagal',
                    'Remote unlock via app dengan WiFi bridge',
                ]),
                'image' => 'products/smart-lock.jpg',
                'gallery' => json_encode(['products/lock-1.jpg', 'products/lock-2.jpg', 'products/lock-3.jpg']),
                'price' => 4100000,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'WSO LED Smart Bulb Pack',
                'slug' => 'wso-led-smart-bulb-pack',
                'category' => 'Lighting',
                'short_description' => 'Paket 4 bohlam LED RGBWW dengan kontrol aplikasi dan 16 juta warna.',
                'description' => 'WSO LED Smart Bulb Pack berisi 4 bohlam LED pintar dengan 16 juta warna dan putih tuneable dari warm 2700K hingga cool 6500K. Setiap bohlam hanya 9W namun setara dengan bohlam 60W konvensional, menghasilkan cahaya 800 lumen. Kontrol via aplikasi, jadwal on/off, dan integrasi dengan asisten suara. Hemat energi hingga 80% dibanding bohlam incandescent.',
                'specifications' => json_encode([
                    'Wattage' => '9W (setara 60W)',
                    'Lumens' => '800lm per bulb',
                    'Color Range' => '16 million colors + tunable white',
                    'Color Temperature' => '2700K - 6500K',
                    'Life Span' => '25,000 hours',
                    'Connectivity' => 'WiFi 2.4GHz, no hub required',
                    'Base Type' => 'E27 Standard',
                ]),
                'features' => json_encode([
                    '16 juta warna RGB + putih tuneable',
                    'Kontrol individual atau grup bohlam',
                    'Schedule on/off & countdown timer',
                    'Music sync mode dengan built-in microphone',
                    'Scene preset: Movie, Reading, Party, dll',
                    'Kompatibel dengan Alexa, Google Home, Siri',
                ]),
                'image' => 'products/smart-bulb.jpg',
                'gallery' => json_encode(['products/bulb-1.jpg', 'products/bulb-2.jpg']),
                'price' => 680000,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'WSO Motion Sensor',
                'slug' => 'wso-motion-sensor',
                'category' => 'Sensors',
                'short_description' => 'Sensor gerak PIR dengan sensitivitas adjustable dan notifikasi real-time.',
                'description' => 'WSO Motion Sensor mendeteksi gerakan dalam radius hingga 8 meter dengan sudut 110°. Sensor PIR (Passive Infrared) ini dapat membedakan pergerakan manusia dari hewan peliharaan kecil, mengurangi alarm palsu. Dengan desain compact dan mounting yang fleksibel, sensor ini dapat diletakkan di meja atau dipasang di dinding. Baterai bertahan hingga 2 tahun dengan penggunaan normal.',
                'specifications' => json_encode([
                    'Detection Range' => '8m, 110° angle',
                    'Technology' => 'PIR (Passive Infrared)',
                    'Pet Immunity' => 'Up to 25kg (adjustable)',
                    'Battery' => 'CR123A, lifetime ~2 years',
                    'Connectivity' => 'Zigbee 3.0 (requires hub)',
                    'Operating Temp' => '-10°C to 45°C',
                    'Dimensions' => '45 x 45 x 35mm',
                ]),
                'features' => json_encode([
                    'Deteksi gerak akurat dengan zona yang dapat disesuaikan',
                    'Filter alarm palsu dari hewan ≤25kg',
                    'Notifikasi push ke smartphone saat terdeteksi',
                    'Integrasi dengan automation rules',
                    'Indikator LED untuk status baterai',
                    'Mounting magnetis untuk instalasi mudah',
                ]),
                'image' => 'products/motion-sensor.jpg',
                'gallery' => json_encode(['products/sensor-1.jpg', 'products/sensor-2.jpg']),
                'price' => 450000,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'name' => 'WSO Smart Doorbell',
                'slug' => 'wso-smart-doorbell',
                'category' => 'Security',
                'short_description' => 'Doorbell video dengan kamera 1080p, two-way audio, dan chime nirkabel.',
                'description' => 'WSO Smart Doorbell memberikan keamanan ekstra dengan kamera 1080p wide-angle, two-way audio yang jernih, dan deteksi visitor berputar ke smartphone Anda. Meskipun tanpa langganan, video dapat disimpan di kartu microSD lokal. Chime nirkabel included dapat diletakkan di mana saja di rumah. Night vision infra-merah memastikan visibility 24/7.',
                'specifications' => json_encode([
                    'Camera' => '1080p Full HD, 160° wide-angle',
                    'Video' => 'H.264, 15fps, night vision IR',
                    'Audio' => 'Two-way with noise cancellation',
                    'Connectivity' => 'WiFi 2.4GHz',
                    'Storage' => 'microSD up to 128GB (local, no subscription)',
                    'Power' => '8-24V AC transformer atau replacer battery pack',
                    'Chime' => 'Wireless, plug-in, 5 volume levels',
                ]),
                'features' => json_encode([
                    'Video call langsung ke smartphone saat ada yang mengetuk',
                    'Deteksi motion dengan zone customization',
                    'Jawaban cepat preset: "Sebentar ya!"',
                    'Night vision untuk visibility di malam hari',
                    'Storage lokal tanpa biaya langganan',
                    'Kompatibel dengan chime nirkabel included',
                ]),
                'image' => 'products/smart-doorbell.jpg',
                'gallery' => json_encode(['products/doorbell-1.jpg', 'products/doorbell-2.jpg']),
                'price' => 1950000,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'WSO Water Leak Sensor',
                'slug' => 'wso-water-leak-sensor',
                'category' => 'Safety',
                'short_description' => 'Sensor kebocoran air dengan alarm buzzer dan notifikasi smartphone.',
                'description' => 'WSO Water Leak Sensor adalah garda depan deteksi kebocoran air yang dapat mencegah kerusakan akibat air sebelum menjadi bencana. Dengan probe sensitif yang mendeteksi air dari segala arah, buzzer 85dB yang membangunkan seluruh rumah, dan notifikasi instant ke smartphone, sensor ini memberikan ketenangan pikiran. Desain IP67 waterproof dan mounting yang fleksibel cocok untuk berbagai lokasi: basement, kamar mandi, dapur, laundry.',
                'specifications' => json_encode([
                    'Detection' => 'Water contact on any probe surface',
                    'Buzzer' => '85dB at 1m',
                    'Battery' => 'CR2, lifetime ~18 months',
                    'Connectivity' => 'Zigbee 3.0 (requires hub)',
                    'Protection' => 'IP67 Waterproof',
                    'Operating Temp' => '0°C to 40°C',
                    'Dimensions' => '50 x 50 x 16mm',
                ]),
                'features' => json_encode([
                    'Deteksi air instan dari segala arah probe',
                    'Alarm buzzer 85dB + notifikasi smartphone',
                    'Automasi: matikan valve air saat terdeteksi kebocoran',
                    'IP67 waterproof untuk instalasi di area basah',
                    'Baterai long-life dengan low-battery alert',
                    'Compact design dengan mounting adhesive atau magnet',
                ]),
                'image' => 'products/water-sensor.jpg',
                'gallery' => json_encode(['products/leak-1.jpg', 'products/leak-2.jpg']),
                'price' => 350000,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 8,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}